server:
  port: 8761
security:
  basic:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  security:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  file: /var/acme_logs/acme-discovery.log